"""APAC Index Rebalance — the cross-market panel (c-231).

Renders `data/index_strategist_qa.json`, which is generated by
`scripts/index_strategist_qa.py`. THE PAGE COMPUTES NOTHING.
Every figure on screen is read from that file, so the website
and the document can never disagree — and if a number here
looks wrong, the fix is in the script, not in the view.

WHAT THIS PAGE IS FOR. A desk covering thirteen APAC markets
has one recurring question before a review: how big is this
going to be, how violent, and when does the move happen. The
Taiwan pages answer that with positioning data. This one
answers it for every market from price and volume alone, and
is explicit that the forecasting half is missing.

THE CAVEAT IS THE PRODUCT. Ten of twelve markets are priced
from a survivors-only source; the panel is unadjusted for
market moves; events in one review are not independent. A page
that showed these numbers without those three facts would be
more impressive and less true.
"""
import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from views import design

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "index_strategist_qa.json"

GREEN, RED, NAVY = "#2e7d52", "#b03a2e", "#1f4e79"
FAINT = "#c9bdb0"

_LABEL = {"HongKong": "Hong Kong", "NewZealand": "New Zealand"}


def _pretty(m):
    return _LABEL.get(m, m)


def _sect(n, title, lead=""):
    design.sect(n, title, lead)


@st.cache_data(show_spinner=False)
def _load():
    if not SRC.exists():
        return None
    return json.loads(SRC.read_text(encoding="utf-8"))


def _q(d, num):
    """One question block by its Q-number."""
    for q in d["questions"]:
        if q["title"].startswith(f"Q{num}."):
            return q
    return None


def _df(rows, cols=None):
    df = pd.DataFrame(rows)
    if "market" in df:
        df["market"] = [_pretty(m) for m in df.market]
    return df[cols] if cols else df


def render():
    d = _load()
    if not d:
        st.info("Run `py scripts\\index_strategist_qa.py` to "
                "build the panel.")
        return

    n = d["n_windows"]
    mk = d["markets"]
    design.status(
        [("Panel", f"{n:,} name-events"),
         ("Markets", len(mk)),
         ("Reviews", "MSCI 2015-2026"),
         ("Inputs", "daily price + volume")],
        right="Tier 1 — no positioning data", state="warn")

    # ---- 1. what this panel is, and is not -----------------
    _sect(1, "What this panel can answer",
          "Thirteen markets, one method, price and volume only.")
    ma = d.get("market_adjustment") or {}
    cov = ma.get("coverage") or {}
    raw_only = ma.get("markets_left_raw") or []
    design.caveat(
        "<b>Three things to carry into every number below.</b> "
        "&nbsp;<b>1.</b> Ten of twelve markets are priced from a "
        "survivors-only source — their DELETION rows are biased "
        "toward names that lived. Taiwan and India come from "
        "exchange day-files and keep the dead; where they "
        "disagree with the others, believe them. &nbsp;"
        "<b>2.</b> Every return is EXCESS over that market's own "
        "local benchmark, with the raw total return kept beside "
        "it. This page used to say the opposite — that no index "
        "series existed for all twelve — and that is no longer "
        "true. &nbsp;<b>3.</b> Names in one review share a "
        "market move, so n counts name-events, not independent "
        "observations."
        + (f" &nbsp;<b>4.</b> Reported RAW for want of benchmark "
           f"coverage: {', '.join(_pretty(m) for m in raw_only)}."
           if raw_only else ""))
    if cov:
        worst = min(cov.items(), key=lambda kv: kv[1]["covered"])
        design.stats([
            {"k": "Benchmarks", "v": f"{len(cov)} of {len(mk)}",
             "s": "local currency"},
            {"k": "Weakest coverage",
             "v": f"{worst[1]['covered']:.1%}",
             "s": _pretty(worst[0])},
            {"k": "Taiwan benchmark", "v": "TAIEX",
             "s": "local file, 99.8% — not Yahoo's 78.6%"},
            {"k": "rev20 horizon", "v": "strict",
             "s": "20 sessions or dropped"}])
    _big = sorted(mk.items(), key=lambda x: -x[1])
    design.stats([
        {"k": "Name-events", "v": f"{n:,}", "s": "2015-2026"},
        {"k": "Markets", "v": str(len(mk)), "s": "MSCI Standard"},
        {"k": "Largest sample", "v": _pretty(_big[0][0]),
         "s": f"{_big[0][1]:,} events"},
        {"k": "Delisted-safe", "v": "2 of 12",
         "s": "Taiwan, India", "kind": "del"}])

    # ---- 2. how big is the print ---------------------------
    q = _q(d, 10)
    _sect(2, "How Big Is the Print",
          "Effective-day volume as a multiple of 20-session "
          "median ADV. This sizes the execution problem before "
          "anything else.")
    rows = q["rows"]
    fig = go.Figure()
    fig.add_bar(
        x=[_pretty(r["market"]) for r in rows],
        y=[r["eff_day_x_adv_median"] for r in rows],
        name="Median", marker_color=NAVY, marker_line_width=0,
        customdata=[[r["n"], r["eff_day_x_adv_p90"]]
                    for r in rows],
        hovertemplate="<b>%{x}</b><br>median %{y:.1f}x ADV"
                      "<br>90th pct %{customdata[1]:.1f}x"
                      "<br>n = %{customdata[0]}<extra></extra>")
    fig.add_bar(
        x=[_pretty(r["market"]) for r in rows],
        y=[(r["eff_day_x_adv_p90"] or 0)
           - (r["eff_day_x_adv_median"] or 0) for r in rows],
        name="to 90th percentile", marker_color=FAINT,
        marker_line_width=0, hoverinfo="skip")
    fig.update_layout(
        barmode="stack", height=380,
        margin=dict(l=0, r=0, t=30, b=0),
        legend=dict(orientation="h", yanchor="bottom", y=1.02,
                    xanchor="right", x=1),
        yaxis=dict(title="multiple of ADV", gridcolor="#f2ebe2"),
        xaxis=dict(title="", showgrid=False))
    design.chart(fig)
    st.caption("Ranked by the 90th percentile. The median is "
               "the day you plan for; the tail is the day that "
               "costs you.")

    # ---- 3. the quiet-event rate ---------------------------
    _sect(3, "How Many Reviews Are Not Events",
          "Share of name-events whose effective-day volume "
          "never reaches twice normal.")
    quiet = sorted(rows, key=lambda r: -(r["share_under_2x"] or 0))
    fig = go.Figure()
    fig.add_bar(
        x=[r["share_under_2x"] for r in quiet],
        y=[_pretty(r["market"]) for r in quiet],
        orientation="h", marker_line_width=0,
        marker_color=[RED if (r["share_under_2x"] or 0) > .3
                      else FAINT for r in quiet],
        customdata=[[r["n"], r["share_over_10x"]] for r in quiet],
        hovertemplate="<b>%{y}</b><br>%{x:.0%} print under 2x ADV"
                      "<br>%{customdata[1]:.0%} print over 10x"
                      "<br>n = %{customdata[0]}<extra></extra>")
    fig.update_layout(
        height=360, margin=dict(l=0, r=0, t=10, b=0),
        showlegend=False,
        xaxis=dict(title="share printing under 2x ADV",
                   tickformat=".0%", gridcolor="#f2ebe2"),
        yaxis=dict(title="", showgrid=False))
    design.chart(fig)
    st.caption("A market above 30% is one where the default "
               "posture on a review name should be that it is "
               "not an event.")

    # ---- 4. violence ---------------------------------------
    q7 = _q(d, 7)
    _sect(4, "Effective-Day Risk",
          "Absolute effective-day return — the move the desk "
          "carries into the close.")
    v = q7["rows"]
    fig = go.Figure()
    for key, colour, nm in (("abs_eff_day_median", NAVY,
                             "median"),
                            ("abs_eff_day_p90", RED,
                             "90th percentile")):
        fig.add_scatter(
            x=[r[key] for r in v],
            y=[_pretty(r["market"]) for r in v],
            mode="markers", name=nm,
            marker=dict(size=11, color=colour),
            customdata=[[r["n"], r["share_over_5pct"]]
                        for r in v],
            hovertemplate="<b>%{y}</b><br>" + nm +
                          " %{x:.1%}<br>%{customdata[1]:.0%} of "
                          "events move over 5%"
                          "<br>n = %{customdata[0]}<extra></extra>")
    for r in v:
        fig.add_shape(type="line", y0=_pretty(r["market"]),
                      y1=_pretty(r["market"]),
                      x0=r["abs_eff_day_median"],
                      x1=r["abs_eff_day_p90"],
                      line=dict(color=FAINT, width=2), layer="below")
    fig.update_layout(
        height=380, margin=dict(l=0, r=0, t=30, b=0),
        legend=dict(orientation="h", yanchor="bottom", y=1.02,
                    xanchor="right", x=1),
        xaxis=dict(title="absolute effective-day return",
                   tickformat=".0%", gridcolor="#f2ebe2"),
        yaxis=dict(title="", showgrid=False))
    design.chart(fig)
    st.caption("The distance between the two dots is the market's "
               "tail. Quote the 90th percentile to a client, not "
               "the median.")

    # ---- 5. where the move happens -------------------------
    q2 = _q(d, 2)
    _sect(5, "Announcement Pop, or the Drift",
          "If the move is in the first session there is nothing "
          "to work. If it is in the drift, there is a window.")
    df = _df(q2["rows"], ["market", "action", "n", "gap1",
                          "drift", "drift_raw",
                          "market_part_of_drift",
                          "total_ann_to_eff",
                          "capture_share_of_move_in_drift"])
    df = df.rename(columns={
        "market": "Market", "action": "Side", "n": "n",
        "gap1": "Announcement Pop", "drift": "Drift (excess)",
        "drift_raw": "Drift (raw)",
        "market_part_of_drift": "Market's Part",
        "total_ann_to_eff": "Total",
        "capture_share_of_move_in_drift": "Share in Drift"})
    for c in ("Announcement Pop", "Drift (excess)", "Drift (raw)",
              "Market's Part", "Total"):
        df[c] = [f"{x:+.2%}" if pd.notna(x) else "—" for x in df[c]]
    df["Share in Drift"] = [
        f"{x:.0%}" if pd.notna(x) else "—"
        for x in df["Share in Drift"]]
    df["Side"] = ["Addition" if s == "ADD" else "Deletion"
                  for s in df["Side"]]
    design.table(
        df, height=420,
        note="<b>Raw = excess + market's part</b>, so the three "
             "columns add across. Where the market's part carries "
             "the OPPOSITE sign to the excess, the raw number was "
             "not merely noisy — it pointed the wrong way, and "
             "that is the case a desk quoting total returns gets "
             "caught by. <b>Share in Drift</b> = drift / (pop + "
             "drift); near 100% means the market takes the whole "
             "window to price the review.")

    # ---- 6. does the print revert --------------------------
    q3 = _q(d, 3)
    _sect(6, "Does the Print Revert",
          "Excess return from the effective close forward. This "
          "is the question the ±20-session panel was built to "
          "answer, and the first time it is asked on a horizon "
          "that is the same length for every event.")
    design.caveat(
        "<b>rev20 is twenty sessions or nothing.</b> It used to "
        "be <code>min(effective + 20, last available)</code>, "
        "which does not fail on a short window — it quietly "
        "returns a 15- or 18-session number and pools it with "
        "the twenties. Read <b>n<sub>20</sub></b> against "
        "<b>n</b>: where they differ, that market still has "
        "windows too short to answer.")
    df = _df(q3["rows"], ["market", "action", "n", "n_rev20",
                          "eff_day", "rev5", "rev20",
                          "rev20_raw", "market_part_of_rev20",
                          "delisted_safe"])
    df = df.rename(columns={
        "market": "Market", "action": "Side", "n": "n",
        "n_rev20": "n₂₀", "eff_day": "Effective Day",
        "rev5": "+5 Sessions", "rev20": "+20 (excess)",
        "rev20_raw": "+20 (raw)",
        "market_part_of_rev20": "Market's Part",
        "delisted_safe": "Keeps the Dead"})
    for c in ("Effective Day", "+5 Sessions", "+20 (excess)",
              "+20 (raw)", "Market's Part"):
        df[c] = [f"{x:+.2%}" if pd.notna(x) else "—" for x in df[c]]
    df["Side"] = ["Addition" if s == "ADD" else "Deletion"
                  for s in df["Side"]]
    df["Keeps the Dead"] = ["yes" if b else "NO"
                            for b in df["Keeps the Dead"]]
    design.table(
        df, height=460,
        note="A deletion bounce on a survivors-only market is the "
             "most biased number on this page — the names that "
             "did not survive cannot bounce. Taiwan and India are "
             "the rows to read.")

    # ---- 7. what beat the close ----------------------------
    q4 = _q(d, 4)
    _sect(7, "Which Schedule Beat the Close",
          "Cost in basis points against printing 100% on the "
          "effective close. Negative beat the benchmark.")
    design.caveat(
        "These are UNCONDITIONAL medians. Taiwan's window "
        "study — the one market where we hold the flow data to "
        "condition on — found early execution won on early-hot "
        "names and LOST on early-cold ones. And "
        "<code>ALL_DAY1</code> puts a print worth 12-40x ADV "
        "into a single close: it measures how much drift there "
        "was, it is not a schedule anyone can run.")
    df = _df(q4["rows"])
    df = df.rename(columns={
        "market": "Market", "action": "Side", "n": "n",
        "LINEAR_bps": "Linear", "ALL_DAY1_bps": "All Day 1",
        "LATE5_bps": "Last 5 Days",
        "EARLY30_MOC70_bps": "30% Early / 70% Close",
        "LINEAR_raw_bps": "Linear (raw)",
        "delisted_safe": "Keeps the Dead"})
    df = df.drop(columns=["MOC_baseline_bps",
                          "ALL_DAY1_raw_bps"])
    df["Side"] = ["Addition" if s == "ADD" else "Deletion"
                  for s in df["Side"]]
    df["Keeps the Dead"] = ["yes" if b else "NO"
                            for b in df["Keeps the Dead"]]
    for c in ("Linear", "All Day 1", "Last 5 Days",
              "30% Early / 70% Close", "Linear (raw)"):
        df[c] = [f"{x:+.0f}" if pd.notna(x) else "—" for x in df[c]]
    design.table(
        df, height=460,
        note="Printing on the effective close is the benchmark "
             "and scores 0 by construction. The headline columns "
             "de-trend the price path by the local index, so they "
             "say what the SCHEDULE cost rather than what the "
             "market did — <b>Linear (raw)</b> is kept beside it "
             "because a schedule that looks cheap in a rising "
             "market is not cheap, it is long the market. A "
             "market whose best column is still positive is one "
             "where nothing here beat simply printing.")

    # ---- 8. per-market brief -------------------------------
    _sect(8, "One Market at a Time",
          "The same panel, arranged for a desk that covers one "
          "market.")
    briefs = {b["market"]: b for b in d.get("briefs", [])}
    if briefs:
        pick = st.selectbox("Market", sorted(briefs),
                            format_func=_pretty,
                            index=sorted(briefs).index("Taiwan")
                            if "Taiwan" in briefs else 0)
        b = briefs[pick]
        if not b["delisted_safe"]:
            design.caveat(
                f"<b>{_pretty(pick)} is priced from a "
                "survivors-only source.</b> Its deletion rows "
                "describe the names that survived being deleted. "
                "Read the addition side with more confidence "
                "than the deletion side.")
        design.stats([
            {"k": "Name-events", "v": f"{b['n']:,}",
             "s": f"{b['reviews']} reviews"},
            {"k": "Median print", "v":
             f"{b['print_median_x_adv']:.1f}x"
             if b["print_median_x_adv"] else "—",
             "s": "of ADV"},
            {"k": "90th pct print", "v":
             f"{b['print_p90_x_adv']:.1f}x"
             if b["print_p90_x_adv"] else "—", "s": "of ADV"},
            {"k": "Not an event", "v":
             f"{b['quiet_rate']:.0%}" if b["quiet_rate"] is not None
             else "—", "s": "print under 2x ADV"}])
        left, right = st.columns(2)
        with left:
            st.markdown("**Additions**")
            design.table(pd.DataFrame([
                {"": "Announcement pop",
                 "value": f"{b['add_gap1']:+.2%}"
                 if b["add_gap1"] is not None else "—"},
                {"": "Drift to the print",
                 "value": f"{b['add_drift']:+.2%}"
                 if b["add_drift"] is not None else "—"},
                {"": "5 days after",
                 "value": f"{b['add_rev5']:+.2%}"
                 if b["add_rev5"] is not None else "—"},
                {"": "Best schedule",
                 "value": f"{b.get('add_best_sched') or '—'}"}]))
        with right:
            st.markdown("**Deletions**")
            design.table(pd.DataFrame([
                {"": "Announcement pop",
                 "value": f"{b['del_gap1']:+.2%}"
                 if b["del_gap1"] is not None else "—"},
                {"": "Drift to the print",
                 "value": f"{b['del_drift']:+.2%}"
                 if b["del_drift"] is not None else "—"},
                {"": "5 days after",
                 "value": f"{b['del_rev5']:+.2%}"
                 if b["del_rev5"] is not None else "—"},
                {"": "Best schedule",
                 "value": f"{b.get('del_best_sched') or '—'}"}]))

    # ---- 8. the limits -------------------------------------
    _sect(9, "What This Page Cannot Tell You",
          "The forecasting half of the Taiwan playbook, and why "
          "it is absent.")
    design.caveat(
        "<b>Everything above is descriptive.</b> None of it "
        "says which name in the NEXT review will be the violent "
        "one. Crowding, completion, squeeze risk, wrong-way "
        "positioning, the anticipation clock and the auction "
        "path all need per-stock positioning or intraday data, "
        "which exists for Taiwan and for no other market here.")
    design.table(pd.DataFrame([
        {"Question": "How big, how violent, when it moves, "
                     "does it revert, which schedule won",
         "Needs": "daily price + volume",
         "Have it?": "all 12 markets"},
        {"Question": "Is the crowd already positioned? Will "
                     "this print be orderly or violent?",
         "Needs": "per-stock borrow + signed flow",
         "Have it?": "Taiwan only"},
        {"Question": "How much went through the auction, and "
                     "did the dislocation decay?",
         "Needs": "intraday 5-minute bars",
         "Have it?": "Taiwan 2023-05+"}]),
        note="Retrieval routes for the missing tiers, with "
             "sources and access notes, are in "
             "<code>docs/APAC_DATA_GAP_REGISTER.md</code>. The "
             "cheapest markets to close the gap are Australia "
             "and Hong Kong — both publish census-quality short "
             "data at open URLs.")

    with st.expander("Method, in full"):
        st.markdown(
            "- **Day 0** is the announcement date's close. MSCI "
            "publishes before the Asian open, so day 0 is "
            "pre-news and day 1 is the first reacting session.\n"
            "- **ADV** is the median volume of the 20 sessions "
            "before day 0.\n"
            "- **T-multiple** is effective-day volume / ADV.\n"
            "- **Drift** runs from day 1 to the session before "
            "the effective print; **effective day** is the "
            "print itself.\n"
            "- **Schedule cost** is signed so that negative "
            "beat the effective close, for both sides.\n"
            "- Windows with fewer than 12 usable sessions are "
            "dropped rather than padded, and no cell is built "
            "from fewer than four events.\n\n"
            f"Generated from `{SRC.name}` by "
            "`scripts/index_strategist_qa.py`. The narrative "
            "read of these tables is in "
            "`docs/INDEX_STRATEGIST_READ_APAC.md`; it is "
            "labelled judgement, not measurement, and is "
            "deliberately NOT asserted on this page.")
