"""c-113 pins: off-cycle-exit verification chain.

The lesson chain this locks in:
  - Yahoo-searched China tickers must sit on the class-implied
    venue (A -> onshore equity ranges; 'AIR CHINA A' -> 0753.HK
    was the H line — 70 wrong venues found and nulled)
  - onshore codes must be EQUITY ranges (510590.SS is an ETF —
    Yahoo returned it for 'PING AN INS A')
  - member names truncate at ~30 chars and can DROP the class
    letter; prefix_match retries without it and the VENUE
    validator disambiguates the A/H twin lines
  - the audit is regenerated by `offcycle_verify.py audit`
    (was ad-hoc in c-111) and must contain no current members
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))


def test_china_class_and_venue_rules():
    from ticker_backfill import _china_class, _china_consistent
    assert _china_class("ANHUI CONCH A (HK-C)") == "A"
    assert _china_class("ANHUI CONCH CEMENT H") == "H"
    assert _china_class("XIAOMI CORP B") == "B"
    # A must be onshore EQUITY (not the H line, not a fund)
    assert not _china_consistent("AIR CHINA A (HK-C)",
                                 "0753.HK")
    assert not _china_consistent("PING AN INS A (HK-C)",
                                 "510590.SS")     # ETF code
    assert _china_consistent("PING AN INS A (HK-C)", "601318")
    assert _china_consistent("ANHUI CONCH A (HK-C)",
                             "600585.SS")
    # H must be the HK line
    assert _china_consistent("ANHUI CONCH CEMENT H", "914")
    assert not _china_consistent("ANHUI CONCH CEMENT H",
                                 "600585")
    # B is ambiguous (HK Class B like Xiaomi vs onshore B)
    assert _china_consistent("XIAOMI CORP B", "1810.HK")


def test_prefix_match_truncation_aware():
    from ticker_backfill import prefix_match
    cand = {"CHINA MERCHANTS SECURITIES CO A": "600999",
            "CHINA MERCHANTS BANK CO LTD A": "600036"}
    # 'SEC' can only prefix SECURITIES, never BANK
    assert prefix_match("CHINA MERCH SEC A (HK-C)",
                        cand) == "600999"
    # dropped-class retry + venue validator disambiguates the
    # truncated A/H twins (the PING AN case)
    twins = {"PING AN INSURANCE (GROUP) OF CHINA": "601318",
             "PING AN INSURANCE (GROUP) CO OF CH": "2318"}
    from ticker_backfill import _china_consistent
    got = prefix_match(
        "PING AN INS A (HK-C)", twins,
        validate=lambda t: _china_consistent(
            "PING AN INS A (HK-C)", t))
    assert got == "601318"
    # without a validator the twins are ambiguous -> None
    assert prefix_match("PING AN INS A (HK-C)", twins) is None


def test_audit_output_state():
    """Pin the on-disk end state of the c-113 verification."""
    import pandas as pd
    oc = pd.read_csv(ROOT / "data" / "offcycle_exit_audit.csv"
                     ).fillna("")
    # parse repair holds: zero candidates touch defective cells
    assert int(oc.touches_defective_cell.sum()) == 0
    # current members must never appear as off-cycle exits
    assert not (oc.security == "PING AN INS A (HK-C)").any()
    assert not (oc.security == "ANHUI CONCH A (HK-C)").any()
    # the audit shrank from 1,171 (c-111) via 1,080 (c-112);
    # ticker-first entity resolution took it under 600
    assert len(oc) < 600
    cl = pd.read_csv(
        ROOT / "data" / "offcycle_exit_classified.csv"
    ).fillna("")
    assert len(cl) == len(oc)
    # the confirmed EO-13959 sanction-wave cluster is present
    assert int(cl.note.str.startswith("EO-13959").sum()) >= 10
    # Hikvision: correct ticker resolved AND genuinely out —
    # the flagship confirmed off-cycle deletion (Jan-2021)
    hik = cl[cl.security.str.contains("HIKVIS")]
    assert len(hik) == 1
    assert hik.iloc[0].note.startswith("EO-13959")
