"""Where one displayed NAME would stand for several securities
(c-241).

Bill: *"'Hyundai Motor Company 005387 / 005380 / 005385' — these
rows have the same company name, why do their tickers differ?
Find out if there are other problems in other datapoints."*

They differ because they ARE different securities: the common
line and two preferred lines. MSCI names them apart; Yahoo
returns the ISSUER name for all three, and the roster preferred
Yahoo's spelling because it is tidier. Tidier and, here, false —
the table showed one company three times.

This finds every other instance. Three kinds turn up and only
the first is safe to rename:

  RENAME       one security, two spellings. Yahoo's name is an
               improvement and merging is correct.
  SHARE_CLASS  common vs preferred vs DVR. Different prices,
               different liquidity, different securities.
  DUAL_LISTING an A-share and its H-share, or a local line and
               its depositary receipt. Different securities on
               different exchanges.

A display that gives the last two a shared name is asserting
something untrue, and every downstream reader inherits it.

Usage:  py scripts\\name_collisions.py
Output: data/name_collisions.json
        docs/NAME_COLLISIONS.md
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
YN = ROOT / "data" / "yahoo_names.json"
OUT = ROOT / "data" / "name_collisions.json"
DOC = ROOT / "docs" / "NAME_COLLISIONS.md"

CLASS_HINT = ("PREF", "PREFERRED", " S1", " S2", "DVR", "NVDR",
              "CLASS A", "CLASS B", " A ", " B ", " H ")
SH_PRE = ("600", "601", "603", "605", "688", "689")
SZ_PRE = ("000", "001", "002", "003", "300", "301")


def _root(t):
    return str(t).split(".")[0].upper()


def classify(tickers, names):
    """Why do these tickers share a name?"""
    roots = {_root(t) for t in tickers}
    # c-241 CORRECTION, caught before this shipped. My first
    # rule was "strip leading zeros; if the codes then match it
    # is one security stored twice". China disproves it:
    # 000598 is Shenzhen (Chengdu Xingrong) and 0598 is Hong
    # Kong (Sinotrans). Depadding merges TWO DIFFERENT
    # COMPANIES — the opposite of the error I was trying to fix,
    # and a worse one, because it invents a history.
    #
    # Padding is only padding WITHIN one code family: a mainland
    # code is six digits, a Hong Kong code is at most five. Two
    # codes of different families are never the same security no
    # matter what the digits do.
    def _fam(r):
        return "CN6" if (r.isdigit() and len(r) == 6) else \
               "HK" if r.isdigit() else "OTHER"
    fams = {_fam(r) for r in roots}
    if len(fams) == 1 and "OTHER" not in fams:
        if len({r.lstrip("0") or "0" for r in roots}) == 1:
            return "PADDING", ("same code with and without "
                               "leading zeros, same code family "
                               "— one security, stored twice")
    mainland = {r for r in roots
                if r.isdigit() and len(r) == 6
                and (r[:3] in SH_PRE or r[:3] in SZ_PRE)}
    hk = {r for r in roots if r.isdigit() and len(r) <= 5}
    if mainland and hk:
        return "DUAL_LISTING", ("an A-share and its H-share: "
                                "two securities, two exchanges, "
                                "two prices")
    joined = " ".join(str(n).upper() for n in names)
    if any(h in joined for h in CLASS_HINT):
        return "SHARE_CLASS", ("common and preferred lines of "
                               "one issuer — different prices "
                               "and liquidity")
    return "UNKNOWN", ("same name, different codes, and no "
                       "structural reason found — worth a look")


def run():
    if not YN.exists():
        print("yahoo_names.json not found")
        return
    yn = json.loads(YN.read_text(encoding="utf-8"))
    by = defaultdict(list)
    for tick, name in yn.items():
        by[re.sub(r"\s+", " ", str(name)).strip().upper()].append(
            tick)
    rows = []
    for name, ticks in sorted(by.items()):
        if len(ticks) < 2:
            continue
        kind, why = classify(ticks, [name])
        rows.append({"display_name": name,
                     "tickers": sorted(ticks),
                     "kind": kind, "why": why})

    from collections import Counter
    kinds = Counter(r["kind"] for r in rows)
    doc = ["# One name, several securities", "",
           "*Generated by `scripts/name_collisions.py`. A "
           "display name that stands for more than one security "
           "makes the table assert something untrue.*", "",
           f"**{len(rows)} display names serve more than one "
           f"ticker.**", "",
           "| kind | count | safe to merge? |",
           "|---|---|---|"]
    safe = {"PADDING": "**yes** — one security, stored twice",
            "RENAME": "yes",
            "SHARE_CLASS": "**NO** — different securities",
            "DUAL_LISTING": "**NO** — different securities",
            "UNKNOWN": "not without looking"}
    for k, n in kinds.most_common():
        doc.append(f"| {k} | {n} | {safe.get(k, '?')} |")
    doc += ["", "## The full list", "",
            "| name | tickers | kind |", "|---|---|---|"]
    for r in rows:
        doc.append(f"| {r['display_name'][:46]} | "
                   f"`{'`, `'.join(r['tickers'][:4])}` | "
                   f"{r['kind']} |")
    doc += ["", "---", "",
            "**What the page does with this (c-241).** The "
            "roster uses Yahoo's name only where it stays "
            "unique within a market. Where it would collide, "
            "MSCI's name is kept — MSCI is the source that "
            "draws the distinction, and the issuer name is "
            "moved into `aka` so the link between the lines is "
            "not lost.", ""]
    DOC.write_text("\n".join(doc), encoding="utf-8")
    OUT.write_text(json.dumps(rows, indent=1), encoding="utf-8")
    print(f"{'kind':14} {'count':>6}")
    for k, n in kinds.most_common():
        print(f"{k:14} {n:>6}")
    print(f"{'TOTAL':14} {len(rows):>6}")
    print(f"\n-> {DOC.relative_to(ROOT)}")
    print(f"-> {OUT.relative_to(ROOT)}")
    return rows


if __name__ == "__main__":
    sys.exit(0 if run() is not None else 1)
