#!/usr/bin/env python3
"""Run a REAL index-rebalance event through the platform's event study and
record it to the event library — turning the demo from synthetic to
evidence. Requires network (yfinance); run LOCALLY, not in CI.

Examples (documented real events — verify dates against announcements):

  # Super Micro joins S&P 500 (announced 2024-03-01, effective 2024-03-18)
  python scripts/run_case_study.py SMCI US "S&P 500" 2024-03-18 --announced 2024-03-01

  # Tesla joins S&P 500 (announced 2020-11-16, effective 2020-12-21) —
  # the classic mega-add; note yfinance history limits on 5-min bars mean
  # older events run on daily data only.
  python scripts/run_case_study.py TSLA US "S&P 500" 2020-12-21 --announced 2020-11-16

  # A recent MSCI Taiwan / Kospi / TOPIX change: take the ticker + effective
  # date from the provider announcement and run the same command.

Outputs: event-study summary to stdout; entry appended to
data/event_library.json (gitignored derived data); optionally a
docs/case_studies/<ticker>_<date>.md summary via --write-doc.
"""
import argparse
import datetime as dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("ticker", help="raw ticker, e.g. SMCI or 2330")
    p.add_argument("market", help="platform market key, e.g. US or 'Taiwan (TWSE)'")
    p.add_argument("index_name", help="e.g. 'S&P 500', 'MSCI Taiwan'")
    p.add_argument("effective", help="effective date YYYY-MM-DD")
    p.add_argument("--announced", help="announcement date YYYY-MM-DD")
    p.add_argument("--window", type=int, default=10, help="days each side of T")
    p.add_argument("--write-doc", action="store_true",
                   help="write docs/case_studies/<ticker>_<date>.md")
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    from agents.rebalancing_event_study import run_event_study
    from agents.trader_view import record_event
    import numpy as np

    eff = dt.date.fromisoformat(a.effective)
    print(f"Running event study: {a.ticker} ({a.market}) — {a.index_name} "
          f"effective {eff} ...")
    es = run_event_study(a.ticker, a.market, eff, a.window, a.index_name,
                         log=lambda m: print(f"  {m}"))
    rel = np.asarray(es.rel_days)
    i_t = int(np.where(rel == 0)[0][0]) if (rel == 0).any() else None
    mult = float(np.asarray(es.ab_vol)[i_t]) if i_t is not None else None
    print("\n=== SUMMARY ===")
    print(f"T-day abnormal volume multiple: "
          f"{mult:.1f}x" if mult else "T-day not in window")
    car = np.asarray(es.car)
    print(f"CAR over window: {car[-1]:+.2%} (pre-effective drift "
          f"{car[i_t] - car[0]:+.2%})" if i_t is not None else "")
    rec = record_event(es, action=f"case study {a.index_name}",
                       t_day_volume_multiple=mult)
    print(f"Recorded to event library (n now includes this event).")
    if a.write_doc:
        out = Path("docs/case_studies")
        out.mkdir(parents=True, exist_ok=True)
        f = out / f"{a.ticker}_{eff}.md"
        f.write_text(
            f"# Case study: {a.ticker} — {a.index_name}, effective {eff}\n\n"
            f"- Announced: {a.announced or 'n/a'}\n"
            f"- T-day abnormal volume multiple: "
            f"{mult:.1f}x\n" if mult else "n/a\n"
            f"- CAR over ±{a.window}d window: {car[-1]:+.2%}\n\n"
            f"Generated by scripts/run_case_study.py — re-run to refresh.\n",
            encoding="utf-8")
        print(f"Wrote {f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
