"""Corrections to security -> ticker, with a reason each (c-259).

WHY A SCRIPT AND NOT A HAND EDIT. `data/security_ticker_map.json`
has 2,918 entries and is regenerated by resolvers. A hand edit
is invisible, unexplained and gets overwritten the next time a
resolver runs. A correction that cannot say WHY it is right is
indistinguishable from the error it replaces.

WHAT THIS FIXES, and how each was proved:

  China|MEITU  3690.HK -> 1357.HK
      3690.HK is MEITUAN, a different company. Meitu Inc is
      1357.HK. Proved externally (HKEX/Bloomberg/Yahoo all
      list Meitu Inc at 1357) and internally: two of the six
      MEITU windows failed with "no data" for 2017 windows,
      which is exactly what a Meituan code does before its
      September-2018 listing. The other FOUR priced — against
      a US$100bn company's tape for a US$5bn company's index
      event. The failures were the lucky half.

  China|ANHUI GUJING DISTILLER B  000596.SZ -> 200596.SZ
      Proved WITHOUT any external source: the changes database
      maps BOTH "ANHUI GUJING A (HK-C)" and "ANHUI GUJING
      DISTILLER B" to 000596.SZ, and two different securities
      cannot share one code. 000596.SZ is the A line; the
      Shenzhen B line of the same issuer is 200596.SZ.

  Australia|BANK OF QUEENSLAND  BOQPG.AX -> BOQ.AX
      BOQPG is a Bank of Queensland PREFERENCE/capital-notes
      line; the ordinary share is BOQ.AX. Bill's instruction
      was to DROP this row because a preference line does not
      belong in an equity rebalance study — correct about the
      instrument, but the row is not a preference-share event.
      MSCI deleted the ORDINARY line; the map simply pointed
      at the wrong listing. Dropping it would discard a real
      index event to hide a ticker defect, so it is repointed
      instead.

NOT FIXED HERE, deliberately. The remaining China gaps are
names truncated past the point of resolution — "QINGDAO HAIER
A (HK-C)" carrying a STAR-board code that listed years after
the review. Guessing those needs an A-share listings file with
listing dates, which is the registered 813-ticker gap. A wrong
guess is worse than a blank, because a blank is visible.

Usage:  py scripts\\ticker_corrections.py         # report
        py scripts\\ticker_corrections.py apply   # write
Then:   py scripts\\changes_db.py build
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAP = ROOT / "data" / "security_ticker_map.json"
LOG = ROOT / "data" / "ticker_corrections.json"

CORRECTIONS = [
    ("China|MEITU", "3690.HK", "1357.HK",
     "3690.HK is Meituan; Meitu Inc is 1357.HK. Four of six "
     "windows priced against the wrong company."),
    ("China|ANHUI GUJING DISTILLER B", "000596.SZ", "200596.SZ",
     "000596.SZ is the A line and is already mapped to ANHUI "
     "GUJING A (HK-C); the B line is 200596.SZ."),
    ("Australia|BANK OF QUEENSLAND", "BOQPG.AX", "BOQ.AX",
     "BOQPG is a preference/capital-notes line; the ordinary "
     "share MSCI deleted is BOQ.AX."),
]


def run(apply=False):
    m = json.loads(MAP.read_text(encoding="utf-8"))
    applied, skipped = [], []
    for key, was, now, why in CORRECTIONS:
        cur = m.get(key)
        if cur == now:
            skipped.append((key, "already corrected"))
            continue
        if cur != was:
            # the map moved under us — do NOT overwrite blind
            skipped.append(
                (key, f"expected {was}, found {cur!r} — left "
                      f"alone, re-verify before forcing"))
            continue
        applied.append({"key": key, "was": was, "now": now,
                        "why": why})
        if apply:
            m[key] = now

    for r in applied:
        print(f"  {r['key']:38s} {r['was']:11s} -> {r['now']}")
        print(f"      {r['why']}")
    for k, r in skipped:
        print(f"  {k:38s} SKIPPED — {r}")

    if apply and applied:
        MAP.write_text(json.dumps(m, indent=1, ensure_ascii=False),
                       encoding="utf-8")
        old = json.loads(LOG.read_text(encoding="utf-8")) if LOG.exists() else []
        LOG.write_text(json.dumps(old + applied, indent=1),
                       encoding="utf-8")
        print(f"\nwrote {MAP.name} and {LOG.name}")
        print("NEXT: py scripts\\changes_db.py build")
    elif applied:
        print("\ndry run — re-run with `apply` to write")
    return applied


if __name__ == "__main__":
    run(apply="apply" in sys.argv[1:])
